trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo java -version
    - bash: echo python --version
    - bash: echo node --version
    - bash: echo mvn -version
    - bash: ls -R $(Build.ArtifactStagingDirectory)
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yml
          **/*.tf
        TargetFolder: '$(Build.AritfactStagingDirectory)'
    - bash: ls -R $(Build.ArtifactStagingDirectory)
# - stage: DevDeploymentJob
#   dependsOn: Build
#   jobs:
#   - job: DevDeploymentJob
#     steps:
#     - bash: echo DevDeploymentJob

# - stage: QADeploymentJob
#   dependsOn: Build
#   jobs:
#   - job: QADeploymentJob
#     steps:
#     - bash: echo QADeploymentJob


# - stage: ProdDeployment
#   dependsOn:
#   - DevDeploymentJob
#   - QADeploymentJob
#   jobs:
#   - job: ProdDeploymentJob
#     steps:
#     - bash: echo ProdDeploymentJob
