trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
  - job: SecondJob
    steps:
    - bash: echo Build SecondJob

- stage: DevDeploymentJob
  jobs:
  - job: DevDeploymentJob
    steps:
    - bash: echo DevDeploymentJob

- stage: QADeploymentJob
  jobs:
  - job: QADeploymentJob
    steps:
    - bash: echo QADeploymentJob


- stage: ProdDeployment
  jobs:
  - job: ProdDeploymentJob
    steps:
    - bash: echo ProdDeploymentJob
