trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    - bash: echo $(Build.BuildNumber)
    - bash: echo $(Build.BuildId)
    - bash: echo $(Build.SourceBranchName)

# - stage: DevDeploymentJob
#   dependsOn: Build
#   jobs:
#   - job: DevDeploymentJob
#     steps:
#     - bash: echo DevDeploymentJob

# - stage: QADeploymentJob
#   dependsOn: Build
#   jobs:
#   - job: QADeploymentJob
#     steps:
#     - bash: echo QADeploymentJob


# - stage: ProdDeployment
#   dependsOn:
#   - DevDeploymentJob
#   - QADeploymentJob
#   jobs:
#   - job: ProdDeploymentJob
#     steps:
#     - bash: echo ProdDeploymentJob
