trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build FirstJob
    # - bash: java -version
    # - bash: python --version
    # - bash: node --version
    # - bash: mvn -version
    # - bash: ls -R $(Build.ArtifactStagingDirectory)

    # - task: PublishBuildArtifacts@1
    #   inputs:
    #     PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    #     ArtifactName: 'drop'
    #     publishLocation: 'Container'

    # - task: CopyFiles@2
    #   inputs:
    #     targetFolder: '$(Build.ArtifactStagingDirectory)'    

    # - task: PublishBuildArtifacts@1    
    #   displayName: 'Publish Artifact: drop'
    #   inputs:
    #     PathtoPublish: '$(build.artifactstagingdirectory)'
